baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Prof. Iuri Ferreira"
        tagline = "Federal University of São Carlos"
        location = "Buri-SP, Brazil"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/iuri-ferreira-35b51938"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/iep-ferreira"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "https://orcid.org/-0001-6567-1970"
            title = "Orcid"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?user=Oa7iIbwAAAAJ&hl=en"
            title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-researchgate"
            url = "https://www.researchgate.net/profile/Iuri-Ferreira"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Iuri has BSc in Health Physics and MSc in Biometrics from São Paulo State University (IBB/UNESP), and PhD in Statistics from University of São Paulo (ESALQ/USP), Brazil. He has experience in design of experiments, regression models, and statistics applied to biological, agricultural, and environmental data. Currently, Iuri is a professor at the Federal University of São Carlos and coordinates the Center of Statistical Modelling on Evironmental Sciences (Ce-MECA), working in the interface between R programming, mathematical modelling, simulation, and statistics."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Assistant Professor"
            dates = "2015 - *Present*"
            company = "Federal University of São Carlos (CCN - UFSCar)"
            details = "Buri-SP. Lagoa do Sino Campus. Contact: iuri@ufscar.br"
            url = "https://www.lagoadosino.ufscar.br/"
        [[params.experience.list]]
            position = "Temporary Lecturer"
            dates = "2013 - 2015"
            url = "http://www.lce.esalq.usp.br/"
            company = "University of São Paulo (ESALQ - USP)"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "DSc in Statistics and Agricultural Experimentation"
        college = "Luiz de Queiroz College of Agriculture (ESALQ), from the University of São Paulo (USP) "
            dates = "2011 - 2015"
            thesis_title = "Smooth piecewise-linear models and applications in agriculture"
        [[params.education.list]]
            degree = "MSc in Biometry"
            college = "Institute of Biological Sciences of Botucatu, São Paulo State University (UNESP)"
            dates = "2009 - 2011"
            thesis_title = "D-optimum experimental designs for the Michaelis-Menten and Hill models"
        [[params.education.list]]
            degree = "BSc in Health Physics"
            college = "Institute of Biological Sciences of Botucatu, São Paulo State University (UNESP)"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Colloidal and Acid Gelling Properties of Mixed Milk and Pea Protein Suspensions"
            authors = "IC Oliveira, IEP Ferreira, F Casanova, ALF Cavallieri, NFN Silva"
            date = "2022"
            journal = "Foods 11 (10)"
            url = "https://www.mdpi.com/2304-8158/11/10/1383"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Phytoregulators and mineral nutrition interactions to the establishment of Passiflora alata seedlings"
            authors = "GH Pinheiro Maciel, IEP Ferreira, D Baron"
            date = "2021"
            journal = "Journal of Plant Nutrition 44 (19), 2825-2839"
            url = "https://www.tandfonline.com/doi/abs/10.1080/01904167.2021.1918715"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Does molybdenum and cobalt foliar spray mitigate nitrate starvation and ammonium deprivation stress?"
            authors = "RA Nunicio Jr, D Baron, IEP Ferreira"
            date = "2021"
            journal = "Revista Brasileira de Fruticultura 43 (4)"
            url = "https://www.scielo.br/j/rbf/a/YsBjVhkKnFdTkmdjFfRVYnM/abstract/?lang=en"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Microbiological water quality monitoring of four ponds from Lagoa do Sino Farm located in São Paulo State, Brazil"
            authors = "PA Evangelista, MAM de Souza, IEP Ferreira, ..."
            date = "2021"
            journal = "Acta Scientiarum. Biological Sciences 43, e52901-e52901"
            url = "https://periodicos.uem.br/ojs/index.php/ActaSciBiolSci/article/view/52901"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "O comportamento do consumidor em tempos de influenciadores digitais"
            authors = "TO Souto, EC de Oliveira, IEP Ferreira"
            date = "2021"
            journal = "Brazilian Journal of Development 7 (3), 30129-30150"
            url = "https://brazilianjournals.com/index.php/BRJD/article/view/26984"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Alternativas para o Desenvolvimento Sustentável do Sudoeste Paulista"
            authors = "NF Nogueira Silva, LL Santos, AC Martensen, IEP Ferreira (Organizers)"
            date = "2021"
            journal = "Editora Científica (ISBN 978-65-5360-020-1)"
            url = "https://www.editoracientifica.org/books/isbn/978-65-5360-020-1 1, 250"
            type = "Books"


        [[params.publication.list]]
            title = "A family of smooth piecewise-linear models with probabilistic interpretations"
            authors = "IEP Ferreira, SS Zocchi"
            date = "2020"
            journal = "arXiv preprint arXiv:2011.07753"
            url = "https://arxiv.org/abs/2011.07753"
            type = "preprint"


        [[params.publication.list]]
            title = "Milk quality, production process and physicochemical characteristics of Porungo, an artisanal cheese from the state of Sao Paulo, Brazil"
            authors = "NFN Silva, KS de Aguiar, NJ Pimentel Filho, IEP Ferreira, ..."
            date = "2020"
            journal = "Journal of Dairy Research 87 (4), 480-483"
            url = "https://www.cambridge.org/core/journals/journal-of-dairy-research/article/abs/milk-quality-production-process-and-physicochemical-characteristics-of-porungo-an-artisanal-cheese-from-the-state-of-sao-paulo-brazil/BA09716E390B413650993E398038415E"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Sound exposure and its beneficial effects on embryonic growth and hatching of broiler chicks"
            authors = "AC Donofre, IJO Da Silva, IEP Ferreira"
            date = "2020"
            journal = "British poultry science 61 (1), 79-85"
            url = "https://www.tandfonline.com/doi/abs/10.1080/00071668.2019.1673315"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Relationship between zooplankton richness and area in Brazilian lakes: comparing natural and artificial lakes and trends"
            authors = "LO Longato, IEP Ferreira, G Perbiche-Neves"
            date = "2018"
            journal = "Acta Limnologica Brasiliensia 30"
            url = "https://www.scielo.br/j/alb/a/48rRKNpSrFjM87kcRg5pBdk/abstract/?lang=en"
            type = "Journal Articles"



        [[params.publication.list]]
            title = "Modelo hierárquico bayesiano na determinação de associação entre marcadores e QTL em uma população F2"
            authors = "RN Pereira, RA LEANDRO, AAF GARCIA, CLS JUNIOR, ..."
            date = "2018"
            journal = "Revista Brasileira de Biometria 36 (2), 414-438"
            url = "https://biometria.ufla.br/index.php/BBJ/article/view/210"
            type = "Journal Articles"
            
            

        [[params.publication.list]]
            title = "Reconciling the Mitscherlich’s law of diminishing returns with Liebig’s law of the minimum. Some results on crop modeling"
            authors = "IEP Ferreira, SS Zocchi, D Baron"
            date = "2017"
            journal = "Mathematical biosciences 293, 29-37"
            url = "https://www.sciencedirect.com/science/article/abs/pii/S0025556417300093"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Mechanical vibrations in the transport of hatching eggs and the losses caused in the hatch and quality of broiler chicks"
            authors = "AC Donofre, IJO da Silva, AC Nazareno, IEP Ferreira"
            date = "2017"
            journal = "Journal of Agricultural Engineering 48 (1), 36-41"
            url = "https://j.agroengineering.org/index.php/jae/article/view/593"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Equilíbrio de cavalos da raça Quarto de Milha participantes da modalidade de três tambores por meio de proporções corporais"
            authors = "AC Donofre, JNP Puoli Filho, IEP Ferreira, MDS Mota, M Chiquitelli Neto"
            date = "2014"
            journal = "Ciência Rural 44 (2), 327-332"
            url = "https://scholar.google.com.br/citations?view_op=view_citation&hl=pt-BR&user=Oa7iIbwAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=Oa7iIbwAAAAJ:zYLM7Y9cAGgC"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Efficient experimental designs for chemical kinetics studies"
            authors = "IEP Ferreira, LA Trinca, CP Ferreira"
            date = "2014"
            journal = "Química Nova 37, 589-596"
            url = "https://www.scielo.br/j/qn/a/Knfq6rJ7wpp67gKqMQqbrCh/abstract/?format=html&lang=en"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Modelling fungus dispersal scenarios using cellular automata"
            authors = "IEP Ferreira, RA Moral, CP Ferreira, WAC Godoy"
            date = "2013"
            journal = "Ecological informatics 14, 53-58"
            url = "https://www.sciencedirect.com/science/article/abs/pii/S1574954112001112"
            type = "Journal Articles"


    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"
