baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Prof. Iuri Ferreira"
        tagline = "Federal University of São Carlos"
        location = "Buri-SP, Brazil"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/iuri-ferreira-35b51938"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/iep-ferreira"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "https://orcid.org/-0001-6567-1970"
            title = "Orcid"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?user=Oa7iIbwAAAAJ&hl=en"
            title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-researchgate"
            url = "https://www.researchgate.net/profile/Iuri-Ferreira"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Iuri has BSc in Health Physics and MSc in Biometrics from São Paulo State University (IBB/UNESP), and PhD in Statistics from University of São Paulo (ESALQ/USP), Brazil. He has experience in design of experiments, regression models, and statistics applied to biological, agricultural, and environmental data. Currently, Iuri is a professor at the Federal University of São Carlos and coordinates the Center of Statistical Modelling on Evironmental Sciences (Ce-MECA), working in the interface between R programming, mathematical modelling, simulation, and statistics."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Assistant Professor"
            dates = "2015 - *Present*"
            company = "Federal University of São Carlos (CCN - UFSCar)"
            details = "Buri-SP. Lagoa do Sino Campus. Contact: iuri@ufscar.br"
            url = "https://www.lagoadosino.ufscar.br/"
        [[params.experience.list]]
            position = "Temporary Lecturer"
            dates = "2013 - 2015"
            url = "http://www.lce.esalq.usp.br/"
            company = "University of São Paulo (ESALQ - USP)"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "DSc in Statistics and Agricultural Experimentation"
        college = "Luiz de Queiroz College of Agriculture (ESALQ), from the University of São Paulo (USP) "
            dates = "2011 - 2015"
            thesis_title = "Smooth piecewise-linear models and applications in agriculture"
        [[params.education.list]]
            degree = "MSc in Biometry"
            college = "Institute of Biological Sciences of Botucatu, São Paulo State University (UNESP)"
            dates = "2009 - 2011"
            thesis_title = "D-optimum experimental designs for the Michaelis-Menten and Hill models"
        [[params.education.list]]
            degree = "BSc in Health Physics"
            college = "Institute of Biological Sciences of Botucatu, São Paulo State University (UNESP)"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Colloidal and Acid Gelling Properties of Mixed Milk and Pea Protein Suspensions"
            authors = "IC Oliveira, IEP Ferreira, F Casanova, ALF Cavallieri, NFN Silva"
            date = "2022"
            journal = "Foods 11 (10)"
            url = "https://www.mdpi.com/2304-8158/11/10/1383"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Phytoregulators and mineral nutrition interactions to the establishment of Passiflora alata seedlings"
            authors = "GH Pinheiro Maciel, IEP Ferreira, D Baron"
            date = "2021"
            journal = "Journal of Plant Nutrition 44 (19), 2825-2839"
            url = "https://www.tandfonline.com/doi/abs/10.1080/01904167.2021.1918715"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Does molybdenum and cobalt foliar spray mitigate nitrate starvation and ammonium deprivation stress?"
            authors = "RA Nunicio Jr, D Baron, IEP Ferreira"
            date = "2021"
            journal = "Revista Brasileira de Fruticultura 43 (4)"
            url = "https://www.scielo.br/j/rbf/a/YsBjVhkKnFdTkmdjFfRVYnM/abstract/?lang=en"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Microbiological water quality monitoring of four ponds from Lagoa do Sino Farm located in São Paulo State, Brazil"
            authors = "PA Evangelista, MAM de Souza, IEP Ferreira, ..."
            date = "2021"
            journal = "Acta Scientiarum. Biological Sciences 43, e52901-e52901"
            url = "https://periodicos.uem.br/ojs/index.php/ActaSciBiolSci/article/view/52901"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "O comportamento do consumidor em tempos de influenciadores digitais"
            authors = "TO Souto, EC de Oliveira, IEP Ferreira"
            date = "2021"
            journal = "Brazilian Journal of Development 7 (3), 30129-30150"
            url = "https://brazilianjournals.com/index.php/BRJD/article/view/26984"
            type = "Journal Articles"


        [[params.publication.list]]
            title = "Alternativas para o Desenvolvimento Sustentável do Sudoeste Paulista"
            authors = "NF Nogueira Silva, LL Santos, AC Martensen, IEP Ferreira (Organizers)"
            date = "2021"
            journal = "Editora Científica (ISBN 978-65-5360-020-1)"
            url = "https://www.editoracientifica.org/books/isbn/978-65-5360-020-1 1, 250"
            type = "Books"








        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"



        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"



        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"



        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"


        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"



    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"
